apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zabbix-mcp-server

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - build.yaml
  - deployment.yaml
  - route.yaml

commonLabels:
  app.kubernetes.io/part-of: zabbix-mcp-server
  app.kubernetes.io/managed-by: kustomize

# OpenShift internal registry image
images:
  - name: zabbix-mcp-server
    newName: image-registry.openshift-image-registry.svc:5000/zabbix-mcp-server/zabbix-mcp-server
    newTag: latest
